config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create, :index, :destroy, :update]
  resources :addresses, only: [:new, :create, :index, :destroy, :update]
  resources :alerts, only: [:create, :index, :update] do
    collection do
      post "notify" => "alerts#notify", :as => :notify
    end
  end
  resources :locations, only: [:show, :create] do
    resources :coordinates, only: :create
  end
end

app/views/pages/_alert_modal.html.erb
<!-- Button trigger modal -->
<button id="alertBtn" type="button" class="btn" data-toggle="modal" data-target="#alertModal"></button>

<!-- Modal -->
<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="alertRadius modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="alertModalLabel"><img class="alert-icon" src="https://res.cloudinary.com/titavon/image/upload/v1615304152/mdi_shield-alert-outline_colour_ygqkjt.png"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>An alert has been sent to your contacts!</p><br>
        <p>Would you like to call the <strong> Police </strong>?</p>
      </div>
      <div class="modal-footer">
        <button id="btnPolice" type="button" class="btn btn-primary">Police</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_create_alert.html.erb
<!-- Modal -->
<div class="modal fade" id="createAlertModal" tabindex="-1" aria-labelledby="createAlertLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="alertRadius modal-content">
      <div class="modal-header alertHeader">
        <h5 class="modal-alert-title" id="createAlertLabel">Create alert!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div>
        <img class="shield-custom" src="https://res.cloudinary.com/titavon/image/upload/v1615564659/mdi_shield-alert-outline_l3z7rj.png">
      </div>

      <div class="modal-body">
        <%= simple_form_for(Alert.new) do |f| %>
          <div class="alert-form-inputs">
            <%= f.input :address,
                        required: true,
                        autofocus: true %>
            </div>
            <div class="alert-container">
              <div class="row">
                <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="robbery" id="Checkbox" name="alert[category]">
                    <label for="Checkbox">
                      <img id="btnRobbery" src="https://res.cloudinary.com/titavon/image/upload/v1615227258/Group_18_z41dxv.png">
                    </label>
                </div>

                 <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="fire arm" id="Checkbox2" name="alert[category]">
                    <label for="Checkbox2">
                      <img id="btnFireArm" src="https://res.cloudinary.com/titavon/image/upload/v1615227258/Group_19_s9tesf.png">
                    </label>
                </div>

                <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="fight" id="Checkbox3" name="alert[category]">
                    <label for="Checkbox3">
                      <img id="btnFight" src="https://res.cloudinary.com/titavon/image/upload/v1615227198/Group_20_w1y3vb.png">
                    </label>
                 </div>

                <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="suspicious" id="Checkbox4" name="alert[category]">
                    <label for="Checkbox4">
                      <img id="btnSuspicious" src="https://res.cloudinary.com/titavon/image/upload/v1615227198/Group_21_cbsp1k.png">
                    </label>
                </div>

                <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="abuse" id="Checkbox5" name="alert[category]">
                    <label for="Checkbox5">
                      <img id="btnAbuse" src="https://res.cloudinary.com/titavon/image/upload/v1615227259/Group_22_ucgxrx.png">
                    </label>
                </div>

                <div class="px-3 col-6 d-flex justify-content-center">
                  <input type="radio" value="kidnap" id="Checkbox6" name="alert[category]">
                    <label for="Checkbox6">
                      <img id="btnKidnap" src="https://res.cloudinary.com/titavon/image/upload/v1615227259/Group_23_xt9gqv.png">
                    </label>
                </div>
              </div>
              <div class="alert-btn-actions btn btn" >
                <%= f.button :submit, "Create" %>
              </div>
            </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/pages/_describe_incident.html.erb
<button type="button" class="incidentbtn btn btn-secondary" data-toggle="modal" data-target="#describeModal">
  Unsafe
</button>



<!-- Modal -->
<div class="modal fade" id="describeModal" tabindex="-1" aria-labelledby="describeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="describeRadius modal-content">
      <div class="greenHeader modal-header">
        <h5 class="modal-title" id="describeModalLabel">Describe your incident</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="exampleFormControlTextarea1"><img class="smiley-describe" src="https://res.cloudinary.com/titavon/image/upload/v1615223500/octicon_smiley-24_caok3k.png"></label>
            <textarea class="form-control textposts" id="exampleFormControlTextarea1" rows="3"></textarea>
             <input class="btn btn-primary post" type="submit" value="Post">
          </div>
       </form>
      </div>
    </div>
  </div>
</div>

app/views/pages/_explanation.html.erb
<!-- Search explanation  -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary search_bar" data-toggle="modal" data-target="#SearchBar">
  Search bar
</button>

<!-- Modal -->
<div class="modal fade" id="SearchBar" tabindex="-1" aria-labelledby="SearchBarLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!--<div class="modal-header">
        <h5 class="modal-title" id="SearchBarLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>-->
      <div class="modal-body searchbar">
        <p>Search fot the safest way to your destination</p>
      </div>
      <!--<div class="modal-footer">-->
        <button type="button" class="btn btn-primary next">Next</button>
      <!--</div>-->
    </div>
  </div>
</div>
<!-- end -->


<!-- 3 dots Button explanation  -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary three" data-toggle="modal" data-target="#threedots">
  3 dots button
</button>

<!-- Modal -->
<div class="modal fade" id="threedots" tabindex="-1" aria-labelledby="threedotsLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!--<div class="modal-header">
        <h5 class="modal-title" id="threedotsLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>-->
      <div class="modal-body three_dots">
        <p>Use the great features that we provide to enshure a Safe way!</p>
      </div>
      <!--<div class="modal-footer">-->
        <button type="button" class="btn btn-primary next">Next</button>
      <!--</div>-->
    </div>
  </div>
</div>
<!-- end -->


<!-- Emergencie button explanation  -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary three" data-toggle="modal" data-target="#emergencie">
  Emegencie button
</button>

<!-- Modal -->
<div class="modal fade" id="emergencie" tabindex="-1" aria-labelledby="emergencieLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!--<div class="modal-header">
        <h5 class="modal-title" id="emergencieLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>-->
      <div class="modal-body emergenciebutton">
        <p>Emegencie Button!</p>
        <p>Send an alert with current location to your emergencie contacts</p>
      </div>
      <!--<div class="modal-footer">-->
        <button type="button" class="btn btn-primary account">Add number</button>
        <button type="button" class="btn btn-secondary skip">Skip</button>
      <!--</div>-->
    </div>
  </div>
</div>
<!-- end -->

app/views/pages/_info_window.html.erb
<h2><%= alert.category %></h2>
<p><%= alert.address %></p>

app/views/pages/_login.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-secondary" data-toggle="modal"  data-target="#LoginModal">
  Log In
</button>

<!-- Login Modal -->
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="LoginModalLabel" aria-hidden="true">
  <div class="log-modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="login-modal-header">

        <button type="button" class="log-close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 class="login-modal-title" id="LoginModalLabel">Log in</h5>
         <div class="login-container text-center">
            <img class="loginicon" src="https://res.cloudinary.com/titavon/image/upload/v1615223484/gg_profile_lg81vl.png">
      </div>
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="log-form-inputs">
          <%= f.input :email,
                      required: false,
                      autofocus: true,
                      input_html: { autocomplete: "email" } %>
          <%= f.input :password,
                      required: false,
                      input_html: { autocomplete: "current-password" } %>
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
        </div>

        <div class="log-form-actions">
          <%= f.button :submit, "Log in", class: "log-btn btn " %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_sidebar.html.erb
<!-- Button trigger modal -->
<button id="sidebar-button" type="button" class="btn" data-toggle="modal" data-target="#sidebarModal"></button>

<% if user_signed_in? %>

  <div class="modal fade sidebarModal" id="sidebarModal" tabindex="-1" aria-labelledby="sidebarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="my-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="smiley-container text-center">
            <img class="smiley" src="https://res.cloudinary.com/titavon/image/upload/v1615223500/octicon_smiley-24_caok3k.png">
            <h1 class="welcome">Welcome <%= current_user.first_name %>!</h1>
          </div> 
        <div class="modal-body">
         <!-- Content of the modal -->
           <ul>
             <li><img class="sidebar-icons" id="contact" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/carbon_phone-voice_vousid.png"><%= link_to "Contacts", contacts_path %></li>
             <hr>
             <li><img class="sidebar-icons" id="saved" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/codicon_home_rdkkd7.png"><%= link_to "Saved Places", addresses_path %></li>
             <hr>
             <li><img class="sidebar-icons" id="profile" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/profile_iusy5f.png"><%= link_to "Profile", edit_user_registration_path %></li>
             <hr>
             <li><img class="sidebar-icons" id="alert" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/mdi_shield-alert-outline_sssntg.png"><%= link_to "Alerts", alerts_path %></li>
             <hr>
             <li><img class="sidebar-icons" id="logout" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/eva_log-out-fill_mngtxt.png"><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item logout" %></li>
           </ul>
        </div>
      </div>
    </div>
  </div>

<% else %>

  <div class="modal fade sidebar" id="sidebarModal" tabindex="-1" aria-labelledby="sidebarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="my-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="smiley-container text-center">
            <img class="smiley" src="https://res.cloudinary.com/titavon/image/upload/v1615223500/octicon_smiley-24_caok3k.png">
            <h1 class="welcome">Welcome</h1> 
          </div> 
          <div class="modal-body">
           <!-- Content of the modal -->
            <ul>
              <li><img class="sidebar-icons" id="contact" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/carbon_phone-voice_vousid.png"><%= link_to "Contacts", contacts_path %></li>
              <hr>
              <li><img class="sidebar-icons" id="saved" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/codicon_home_rdkkd7.png"><%= link_to "Saved Places", addresses_path %></li>
              <hr>
              <li><img class="sidebar-icons" id="profile" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/profile_iusy5f.png"><%= link_to "Profile", edit_user_registration_path %></li>
              <hr>
              <li><img class="sidebar-icons" id="alert" src="https://res.cloudinary.com/titavon/image/upload/v1615236183/mdi_shield-alert-outline_sssntg.png"><%= link_to "Alerts", alerts_path %></li>
              <div class="buttons-center">
                  <%= render "login" %>
                  <%= render "signup" %>
              </div>
            </ul>
          </div>
      </div>
    </div>
  </div>

<% end %>

app/views/pages/_signup.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#SignupModal">
  Sign Up
</button>

<!-- Signup Modal -->
<div class="modal fade" id="SignupModal" tabindex="-1" aria-labelledby="SignupModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="SignupModalLabel">Create your account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="signup-container text-center">
            <img class="signupicon" src="https://res.cloudinary.com/titavon/image/upload/v1615223484/gg_profile_lg81vl.png">
      </div>
      <div class="modal-body">
        <div class="signupicon" style="position: absolute; height: 50px; width: 50px;" ></div>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>

          <div class="up-form-inputs">
            <%= f.input :first_name,
                        required: true,
                        autofocus: true %>
            <%= f.input :last_name,
                        required: true,
                        autofocus: true %>
            <%= f.input :email,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
            <%= f.input :phone_number,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "phone_number" } %>
            <%= f.input :username,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "username" } %>
            <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" } %>
            <%= f.input :password_confirmation,
                        required: true,
                        input_html: { autocomplete: "new-password" } %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Create", class: "btn btn-primary create" %>
          </div>
        <% end %>
      </div>
     <!--  <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/pages/_trip_review.html.erb
<!-- Modal -->
<div class="modal fade review" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="reviewRadius modal-content">
      <div class="tripReviewGreen modal-header">
        <div class="trip-container text-center">
          <img class="trip-icon" src="https://res.cloudinary.com/titavon/image/upload/v1615257074/Vector_vxcbrz.png">
        </div>
      </div>
      <div class="modal-body">
        <h5 class="modal-title" id="reviewModalLabel">How was your trip?</h5>
        <div class="buttons-review">
          <button class="btn btn-primary" id="btnGood" data-dismiss="modal" type="button">Good!</button>
          <button class="btn btn-secondary" id="btnUnsafe" type="button" data-toggle="modal" data-target="#createAlertModal">Unsafe</button>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "create_alert" %>

app/views/pages/home.html.erb
<div id="map" data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>" data-markers="<%= @markers.to_json %>"></div>
<div class="sidebar">
  <div id="reports" class="reports"></div>
</div>

<div style="position: absolute;top: 0; left:0;">

  <%= render "sidebar" %>
</div>


<div style="position: absolute; bottom: 0; right: 0;" class="mb-4 mr-3" >
  <%= render "alert_modal" %>
</div>

  <% #= render "describe_incident" %>
  <button type="button" class="btn btn-primary" id="reviewdestination" style="display: hidden;" data-toggle="modal" data-target="#reviewModal"></button>
  <%= render "trip_review" %>

<div class="btn-group dropup mb-5 ml-4" style="position: absolute; bottom: 0; left: 0; ">
  <button id="dot-menu-btn" type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>

  <div class="dropdown-menu border-0 bg-transparent" >
    <!-- Dropdown menu links -->

    <div class="createalert">
      <button id="create-alert" type="button" class="btn" data-toggle="modal" data-target="#createAlertModal"></button>
    </div>

    <div class="my-location">
      <%= link_to contacts_path do %> 
       <button id="myLocation" class="btn" data-user="<%= current_user.id if current_user %>"></button>
       <% end %>
    </div>
  </div>
</div>


<%= render "create_alert", alert: @alert %>