config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create, :index, :destroy, :update]
  resources :addresses, only: [:new, :create, :index, :destroy, :update]
  resources :alerts, only: [:create, :index, :update] do
    collection do
      post "notify" => "alerts#notify", :as => :notify
    end
  end
  resources :locations, only: [:show, :create] do
    resources :coordinates, only: :create
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name, :phone_number, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: %i[update destroy]

  def index
    @contacts = Contact.all.where(user: current_user)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user

    redirect_to contacts_path if @contact.save
  end

  def update
    @contact.update(contact_params)
  end

  def destroy
    @contact.destroy
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number, :email, :emergency_contact)
  end
end

app/views/contacts/index.html.erb
<%= link_to root_path do %>
  <img class="goback" src="https://res.cloudinary.com/titavon/image/upload/v1615237711/Vector_pdzyn9.png">
<% end %>

<br>

<hr>

<body>
  <h1 class="contacts">Contacts</h1>

<div>
  <div class= "name d-flex w-50">
    <%= form_tag contacts_path, method: :get, class: "simple_form search", id: "contact-search" do %>
      <div class="search-contacts-form-control form-group">
        <%= text_field_tag :query,
                           params[:query],
                           class: "form-control string required pl-5",
                           placeholder: "Search" %>
          <button id="search-contacts" name="button" type="submit" class="btn">
            <img  id="search-icon" style=" height: 20px; width: 20px;" src="https://res.cloudinary.com/titavon/image/upload/v1615305713/Vector_1_qidu3w.png">
          </button>
        <% end %>
      </div>

    <div class="ml-2">
      <%= link_to new_contact_path do %>
        <button type="button" class="add-contact-btn"></button>
      <% end %>
    </div>
  </div>
</div>

  <% @contacts.each do |contact| %>
    <hr>
    <button class= "contact-container btn d-flex justify-content-between w-100 p-2 contact" data-contact="<%= contact.id %>" data-user="<%= current_user.id if current_user %>">
      <div class= "name d-flex w-50">
        <div>
          <%= contact.first_name %>
        </div>
        <div class="ml-2">
          <%= contact.last_name %>
        </div>
      </div>
      <% if contact.emergency_contact == true %>
        <img class="contact-emergency" src="https://res.cloudinary.com/titavon/image/upload/v1615240825/Group_26_fnitto.png">
      <% end %>
    </button>
  <% end %>
</body>

app/views/contacts/new.html.erb
 <%= link_to contacts_path do %>
  <img class="goback" src="https://res.cloudinary.com/titavon/image/upload/v1615237711/Vector_pdzyn9.png">
 <% end %>
<br>

<hr>

<h1 class="create-contact">Create new Contact</h1>

<%= simple_form_for(@contact) do |f| %>
  <div class="form-inputs">
    <%= f.input :first_name,
                required: true,
                autofocus: true %>
    <%= f.input :last_name,
                required: true,
                autofocus: true %>
    <%= f.input :phone_number,
                required: true,
                autofocus: true %>
    <%= f.input :email,
                required: true,
                autofocus: true %>
    <div class="is-emergency">
    <%= f.input :emergency_contact,
                required: true,
                autofocus: true %>
    </div>
    <div class="btn-actions btn">
      <%= f.button :submit, "Create" %>
    </div>
  </div>
<% end %>