config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts, only: [:new, :create, :index, :destroy, :update]
  resources :addresses, only: [:new, :create, :index, :destroy, :update]
  resources :alerts, only: [:create, :index, :update] do
    collection do
      post "notify" => "alerts#notify", :as => :notify
    end
  end
  resources :locations, only: [:show, :create] do
    resources :coordinates, only: :create
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_address, only: %i[update destroy]

  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user

    redirect_to addresses_path if @address.save
  end

  def update
    @address.update(address_params)
  end

  def destroy
    @address.destroy
  end

  private

  def find_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:address, :label, :latitude, :longitude)
  end
end

app/views/addresses/index.html.erb
 <%= link_to root_path do %>
  <img class="goback" src="https://res.cloudinary.com/titavon/image/upload/v1615237711/Vector_pdzyn9.png">
 <% end %>
<br>
<hr>
<h1 class="address-title">Saved places</h1>

<div>
  <div class= "name d-flex w-50">
    <%= form_tag addresses_path, method: :get, class: "simple_form search", id: "contact-search" do %>
      <div class="address-search-form-control form-group">
        <%= text_field_tag :query,
                           params[:query],
                           class: "form-control string required pl-5",
                           placeholder: "Search" %>
          <button id="search-address" name="button" type="submit" class="btn">
            <img  id="search-icon" style=" height: 20px; width: 20px;" src="https://res.cloudinary.com/titavon/image/upload/v1615305713/Vector_1_qidu3w.png">
          </button>
        <% end %>
      </div>

    <div class="ml-2">
      <%= link_to new_address_path do %>
        <button type="button" class="add-contact-btn"></button>
      <% end %>
    </div>
  </div>
</div>


<% @addresses.each do |address| %>
<hr>

    <div class="each-address">
      <%= address.label %>
    </div>

    <div class="address-description">
      <%= address.address %>
    </div>

<% end %>

app/views/addresses/new.html.erb
 <%= link_to addresses_path do %>
  <img class="goback" src="https://res.cloudinary.com/titavon/image/upload/v1615237711/Vector_pdzyn9.png">
 <% end %>
<br>
<hr>
<h1 class="title-new-address">Save address</h1>

 <div class="address-form-inputs">
  <%= simple_form_for(@address) do |f| %>
      <%= f.input :label,
                  required: true,
                  autofocus: true %>
      <%= f.input :address %>

    <div class="address-btn-actions btn ">
      <%= f.button :submit, "Create" %>
    </div>
  <% end %>
</div>